HTTP/1.1 200 OK
Content-Type: text/xml
Transfer-Encoding: chunked

<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://connect.webfleet.tomtomwork.com/services" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="objectsAndPeopleReportingService" targetNamespace="http://connect.webfleet.tomtomwork.com/services">
  <wsdl:types>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://connect.webfleet.tomtomwork.com/transfer" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns2="http://connect.webfleet.tomtomwork.com/parameters" xmlns:ns1="http://connect.webfleet.tomtomwork.com/parameters/objects" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://connect.webfleet.tomtomwork.com/transfer">
<import xmlns="http://www.w3.org/2001/XMLSchema" namespace="http://www.w3.org/2001/XMLSchema-instance"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/parameters/objects"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/parameters"/>
<xs:complexType name="NearestVehicleTO">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="objectNo" type="xs:string"/>
<xs:element minOccurs="0" name="objectUid" type="xs:string"/>
<xs:element minOccurs="0" name="objectState" nillable="true" type="ns1:objectState"/>
<xs:element minOccurs="0" name="latitude" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="longitude" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="linearDistance" nillable="true" type="xs:long"/>
<xs:element minOccurs="0" name="routeDistance" nillable="true" type="xs:long"/>
<xs:element minOccurs="0" name="routeTime" nillable="true" type="xs:int"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="TransferObjectBase">
<xs:sequence/>
</xs:complexType>
<xs:complexType name="GenericServiceQueryOpResult">
<xs:complexContent>
<xs:extension base="tns:ServiceQueryOpResult">
<xs:sequence>
<xs:element minOccurs="0" name="results" nillable="true">
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="resultItem" type="tns:TransferObjectBase"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ServiceQueryOpResult">
<xs:complexContent>
<xs:extension base="tns:ServiceOpResult">
<xs:sequence>
<xs:element default="0" name="resultSize" type="xs:int"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType abstract="true" name="ServiceOpResult">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element default="-1" name="statusCode" type="xs:int"/>
<xs:element minOccurs="0" name="statusMessage" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="errors" nillable="true">
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="errorInfo" type="tns:ErrorInfo"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ErrorInfo">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element default="" name="msg" type="xs:string"/>
</xs:sequence>
<xs:attribute name="objectName" type="xs:string"/>
<xs:attribute name="fieldName" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="GenericServiceWriteOpResult">
<xs:complexContent>
<xs:extension base="tns:ServiceWriteOpResult">
<xs:sequence>
<xs:element minOccurs="0" name="failed" nillable="true" type="tns:TransferObjectBase"/>
<xs:element minOccurs="0" name="succeeded" nillable="true" type="tns:TransferObjectBase"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ServiceWriteOpResult">
<xs:complexContent>
<xs:extension base="tns:ServiceOpResult">
<xs:sequence/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ObjectFeatureTO">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="objectNo" type="xs:string"/>
<xs:element minOccurs="0" name="objectUid" type="xs:string"/>
<xs:element minOccurs="0" name="feature" nillable="true" type="ns1:ObjectFeatureType"/>
<xs:element minOccurs="0" name="volumeMax" nillable="true" type="xs:long"/>
<xs:element minOccurs="0" name="volumeUsed" nillable="true" type="xs:long"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="SwitchOutputTO">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="objectNo" type="xs:string"/>
<xs:element minOccurs="0" name="objectUid" type="xs:string"/>
<xs:element minOccurs="0" name="status" type="xs:int"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="Contract">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="contractNo" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="beginDate" type="xs:dateTime"/>
<xs:element minOccurs="0" name="endDate" type="xs:dateTime"/>
<xs:element minOccurs="0" name="tariffName" type="xs:string"/>
<xs:element minOccurs="0" name="referenceNo" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="Sim">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="iccid" type="xs:string"/>
<xs:element minOccurs="0" name="roamingEnabled" type="xs:boolean"/>
<xs:element minOccurs="0" name="msisdn" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="Obu">
<xs:complexContent>
<xs:extension base="tns:DeviceIdentity">
<xs:sequence>
<xs:element minOccurs="0" name="osVersion" type="xs:string"/>
<xs:element minOccurs="0" name="appVersion" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DeviceIdentity">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="type" type="xs:string"/>
<xs:element minOccurs="0" name="serialNo" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="Pnd">
<xs:complexContent>
<xs:extension base="tns:DeviceIdentity">
<xs:sequence>
<xs:element minOccurs="0" name="ncVersion" type="xs:string"/>
<xs:element minOccurs="0" name="appVersion" type="xs:string"/>
<xs:element minOccurs="0" name="mapVersions">
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="mapVersion" nillable="true" type="tns:MapInfo"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="MapInfo">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="name" type="xs:string"/>
<xs:element minOccurs="0" name="version" type="xs:string"/>
<xs:element minOccurs="0" name="active" type="xs:boolean"/>
<xs:element minOccurs="0" name="formattedName" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="RoutingData">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element name="endDateTime" type="xs:dateTime"/>
<xs:element name="endDay" type="ns2:RouteDay"/>
<xs:element name="distance" type="xs:long"/>
<xs:element name="time" type="xs:int"/>
<xs:element minOccurs="0" name="endTime" type="xs:string"/>
<xs:element name="delay" type="xs:long"/>
<xs:element name="timeZoneOffset" type="xs:long"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="KeyValuePair">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence/>
<xs:attribute name="key" type="xs:string"/>
<xs:attribute name="value" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverVehicleAssignment">
<xs:complexContent>
<xs:extension base="tns:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="driverNo" type="xs:string"/>
<xs:element minOccurs="0" name="objectNo" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
</xs:schema>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://connect.webfleet.tomtomwork.com/transfer/objects" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns4="http://connect.webfleet.tomtomwork.com/transfer/positions" xmlns:ns3="http://connect.webfleet.tomtomwork.com/parameters/objects" xmlns:ns2="http://connect.webfleet.tomtomwork.com/transfer/addresses" xmlns:ns1="http://connect.webfleet.tomtomwork.com/transfer" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://connect.webfleet.tomtomwork.com/transfer/objects">
<import xmlns="http://www.w3.org/2001/XMLSchema" namespace="http://www.w3.org/2001/XMLSchema-instance"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer/addresses"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/parameters/objects"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer/positions"/>
<xs:complexType name="ObjectGroupIdentity">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence/>
<xs:attribute name="name" type="xs:string" use="required"/>
<xs:attribute name="objectCount" type="xs:int"/>
<xs:attribute name="objectGroupUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ObjectGroupObjectRelation">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element name="objectGroup" type="tns:ObjectGroupIdentity"/>
<xs:element name="object" type="tns:BasicObject"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="BasicObject">
<xs:complexContent>
<xs:extension base="tns:ObjectIdentity">
<xs:sequence>
<xs:element minOccurs="0" name="objectName" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ObjectIdentity">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence/>
<xs:attribute name="objectNo" type="xs:string"/>
<xs:attribute name="objectUid" type="xs:string"/>
<xs:attribute name="externalId" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverReport">
<xs:complexContent>
<xs:extension base="tns:DriverIdentity">
<xs:sequence>
<xs:element minOccurs="0" name="driverCode" type="xs:string"/>
<xs:element minOccurs="0" name="personName" nillable="true" type="tns:PersonName"/>
<xs:element minOccurs="0" name="email" type="xs:string"/>
<xs:element minOccurs="0" name="description" type="xs:string"/>
<xs:element minOccurs="0" name="company" type="xs:string"/>
<xs:element minOccurs="0" name="location" nillable="true" type="ns2:BasicLocation"/>
<xs:element minOccurs="0" name="phoneNumbers" nillable="true" type="ns2:PhoneContact"/>
<xs:element minOccurs="0" name="currentVehicle" nillable="true" type="tns:BasicObject"/>
<xs:element minOccurs="0" name="assignedTocurrentVehicleSince" nillable="true" type="xs:dateTime"/>
<xs:element minOccurs="0" name="currentWorkState" nillable="true" type="ns3:WorkState"/>
<xs:element minOccurs="0" name="signOnRole" nillable="true" type="ns3:DriverRole"/>
<xs:element minOccurs="0" name="dtCardId" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="dtCardCountry" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="rllButtonId" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="currentWorkingTime" nillable="true" type="xs:long"/>
<xs:element minOccurs="0" name="currentWorkingTimeStart" nillable="true" type="xs:dateTime"/>
<xs:element minOccurs="0" name="currentWorkingTimeEnd" nillable="true" type="xs:dateTime"/>
<xs:element minOccurs="0" name="addr" type="ns2:AddressIdentity"/>
<xs:element minOccurs="0" name="addrPos" type="ns4:BasicGeoPosition"/>
<xs:element minOccurs="0" name="manualAssignment" nillable="true" type="xs:boolean"/>
<xs:element minOccurs="0" name="pin" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverIdentity">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence/>
<xs:attribute name="driverNo" type="xs:string"/>
<xs:attribute name="driverUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="PersonName">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="name1" type="xs:string"/>
<xs:element minOccurs="0" name="name2" type="xs:string"/>
<xs:element minOccurs="0" name="name3" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ObjectReport">
<xs:complexContent>
<xs:extension base="tns:BasicObject">
<xs:sequence>
<xs:element minOccurs="0" name="objectClassName" type="xs:string"/>
<xs:element minOccurs="0" name="objectType" type="xs:string"/>
<xs:element minOccurs="0" name="description" type="xs:string"/>
<xs:element minOccurs="0" name="lastMsgId" type="xs:long"/>
<xs:element minOccurs="0" name="lastMsgTime" type="xs:dateTime"/>
<xs:element minOccurs="0" name="deleted" type="xs:boolean"/>
<xs:element minOccurs="0" name="position" nillable="true" type="ns4:GeoPosition"/>
<xs:element minOccurs="0" name="positionText" type="xs:string"/>
<xs:element minOccurs="0" name="positionTextShort" type="xs:string"/>
<xs:element minOccurs="0" name="speed" type="xs:int"/>
<xs:element minOccurs="0" name="course" type="xs:int"/>
<xs:element minOccurs="0" name="direction" type="ns4:IntercardinalDirections"/>
<xs:element minOccurs="0" name="quality" type="xs:string"/>
<xs:element minOccurs="0" name="satellite" type="xs:string"/>
<xs:element minOccurs="0" name="status" type="xs:string"/>
<xs:element minOccurs="0" name="navDestination" type="ns4:NavDestination"/>
<xs:element minOccurs="0" name="driverCurrentWorkState" nillable="true" type="ns3:WorkState"/>
<xs:element minOccurs="0" name="coDriverCurrentWorkState" nillable="true" type="ns3:WorkState"/>
<xs:element minOccurs="0" name="driver" nillable="true" type="tns:DriverIdentity"/>
<xs:element minOccurs="0" name="coDriver" nillable="true" type="tns:DriverIdentity"/>
<xs:element minOccurs="0" name="rllBTAddress" type="xs:string"/>
<xs:element minOccurs="0" name="ignitionState" type="xs:int"/>
<xs:element minOccurs="0" name="odometer" type="xs:int"/>
<xs:element minOccurs="0" name="distanceToDestination" type="xs:int"/>
<xs:element minOccurs="0" name="tripMode" type="xs:int"/>
<xs:element minOccurs="0" name="standstillState" type="xs:int"/>
<xs:element minOccurs="0" name="ignitionTime" type="xs:dateTime"/>
<xs:element minOccurs="0" name="pndConnected" type="xs:int"/>
<xs:element minOccurs="0" name="orderNo" type="xs:string"/>
<xs:element minOccurs="0" name="driverName" type="xs:string"/>
<xs:element minOccurs="0" name="driverTelMobile" type="xs:string"/>
<xs:element minOccurs="0" name="coDriverName" type="xs:string"/>
<xs:element minOccurs="0" name="coDriverTelMobile" type="xs:string"/>
<xs:element minOccurs="0" name="posTime" type="xs:dateTime"/>
<xs:element minOccurs="0" name="fuelLevel" type="xs:int"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="MobileObject">
<xs:complexContent>
<xs:extension base="tns:BasicObject">
<xs:sequence>
<xs:element minOccurs="0" name="mobileObjectType" type="tns:MobileObjectType"/>
<xs:element minOccurs="0" name="licensePlate" type="xs:string"/>
<xs:element minOccurs="0" name="type" type="xs:string"/>
<xs:element minOccurs="0" name="width" type="xs:string"/>
<xs:element minOccurs="0" name="length" type="xs:string"/>
<xs:element minOccurs="0" name="height" type="xs:string"/>
<xs:element minOccurs="0" name="maxweight" type="xs:string"/>
<xs:element minOccurs="0" name="netweight" type="xs:string"/>
<xs:element minOccurs="0" name="netload" type="xs:string"/>
<xs:element minOccurs="0" name="power" type="xs:string"/>
<xs:element minOccurs="0" name="numAxes" type="xs:string"/>
<xs:element minOccurs="0" name="identNumber" type="xs:string"/>
<xs:element minOccurs="0" name="registrationDate" type="xs:string"/>
<xs:element minOccurs="0" name="averageVehicleFuelUsage" type="xs:int"/>
<xs:element minOccurs="0" name="averageEPFuelUsage" type="xs:int"/>
<xs:element minOccurs="0" name="averageFleetFuelUsage" type="xs:int"/>
<xs:element minOccurs="0" name="vehicleFuelType" type="ns3:FuelType"/>
<xs:element minOccurs="0" name="epFuelType" type="ns3:FuelType"/>
<xs:element minOccurs="0" name="fleetFuelType" type="ns3:FuelType"/>
<xs:element minOccurs="0" name="engineSize" type="xs:int"/>
<xs:element minOccurs="0" name="epBTAddress" type="xs:string"/>
<xs:element minOccurs="0" name="vehicleColor" type="ns3:VehicleColour"/>
<xs:element minOccurs="0" name="speedLimit" type="xs:float"/>
<xs:element minOccurs="0" name="description" type="xs:string"/>
<xs:element minOccurs="0" name="vehicleRpmLimit" type="xs:int"/>
<xs:element minOccurs="0" name="fleetRpmLimit" type="xs:int"/>
<xs:element minOccurs="0" name="fuelTankSize" type="xs:int"/>
<xs:element minOccurs="0" name="obuBTAddress" type="xs:string"/>
<xs:element minOccurs="0" name="epType" type="ns3:EpType"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="WakeupTimersTO">
<xs:complexContent>
<xs:extension base="tns:ObjectIdentity">
<xs:sequence>
<xs:element minOccurs="0" name="time1" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="time2" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="time3" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="time4" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="time5" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="mon" nillable="true" type="xs:boolean"/>
<xs:element minOccurs="0" name="tue" nillable="true" type="xs:boolean"/>
<xs:element minOccurs="0" name="wed" nillable="true" type="xs:boolean"/>
<xs:element minOccurs="0" name="thu" nillable="true" type="xs:boolean"/>
<xs:element minOccurs="0" name="fri" nillable="true" type="xs:boolean"/>
<xs:element minOccurs="0" name="sat" nillable="true" type="xs:boolean"/>
<xs:element minOccurs="0" name="sun" nillable="true" type="xs:boolean"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ContractDevice">
<xs:complexContent>
<xs:extension base="tns:ObjectIdentity">
<xs:sequence>
<xs:element minOccurs="0" name="contract" type="ns1:Contract"/>
<xs:element minOccurs="0" name="activationKey" type="xs:string"/>
<xs:element minOccurs="0" name="sim" type="ns1:Sim"/>
<xs:element minOccurs="0" name="obu" type="ns1:Obu"/>
<xs:element minOccurs="0" name="pnd" type="ns1:Pnd"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="objectDetails">
<xs:complexContent>
<xs:extension base="tns:ObjectIdentity">
<xs:sequence>
<xs:element minOccurs="0" name="vehicleType" nillable="true" type="ns3:VehicleType"/>
<xs:element minOccurs="0" name="vehicleColor" nillable="true" type="ns3:VehicleColour"/>
<xs:element minOccurs="0" name="identNumber" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="registrationDate" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="denotation" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="licensePlateNumber" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="speedLimit" nillable="true" type="xs:float"/>
<xs:element minOccurs="0" name="fuelConsumption" nillable="true" type="xs:float"/>
<xs:element minOccurs="0" name="fuelType" nillable="true" type="ns3:FuelType"/>
<xs:element minOccurs="0" name="netWeight" nillable="true" type="xs:float"/>
<xs:element minOccurs="0" name="maxWeight" nillable="true" type="xs:float"/>
<xs:element minOccurs="0" name="netLoad" nillable="true" type="xs:float"/>
<xs:element minOccurs="0" name="numAxles" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="length" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="width" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="height" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="description" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="power" nillable="true" type="xs:float"/>
<xs:element minOccurs="0" name="engineSize" type="xs:int"/>
<xs:element minOccurs="0" name="rpmLimit" type="xs:int"/>
<xs:element minOccurs="0" name="fuelTankSize" type="xs:int"/>
<xs:element minOccurs="0" name="epBTAddress" type="xs:string"/>
<xs:element minOccurs="0" name="epType" type="ns3:EpType"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="UpdateContractInfo">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="object" type="tns:ObjectIdentity"/>
<xs:element minOccurs="0" name="referenceNo" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="Driver">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="driverNo" type="xs:string"/>
<xs:element minOccurs="0" name="name" type="xs:string"/>
<xs:element minOccurs="0" name="name2" type="xs:string"/>
<xs:element minOccurs="0" name="name3" type="xs:string"/>
<xs:element minOccurs="0" name="code" type="xs:string"/>
<xs:element minOccurs="0" name="country" type="xs:string"/>
<xs:element minOccurs="0" name="zip" type="xs:string"/>
<xs:element minOccurs="0" name="city" type="xs:string"/>
<xs:element minOccurs="0" name="street" type="xs:string"/>
<xs:element minOccurs="0" name="telMobile" type="xs:string"/>
<xs:element minOccurs="0" name="telPrivate" type="xs:string"/>
<xs:element minOccurs="0" name="email" type="xs:string"/>
<xs:element minOccurs="0" name="description" type="xs:string"/>
<xs:element minOccurs="0" name="company" type="xs:string"/>
<xs:element minOccurs="0" name="pin" type="xs:string"/>
<xs:element minOccurs="0" name="dtCardId" type="xs:string"/>
<xs:element minOccurs="0" name="dtCardCountry" type="xs:string"/>
<xs:element minOccurs="0" name="newDriverNo" type="xs:string"/>
<xs:element minOccurs="0" name="rllButtonId" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="addressNo" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverGroup">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="driverGroupName" type="xs:string"/>
<xs:element minOccurs="0" name="driverGroupUid" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverGroupDriverRelationship">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="driverNo" type="xs:string"/>
<xs:element minOccurs="0" name="groupName" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="BasicDriver">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="driverName" type="xs:string"/>
</xs:sequence>
<xs:attribute name="driverNo" type="xs:string"/>
<xs:attribute name="driverUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverIdentityAndName">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence/>
<xs:attribute name="driverNo" type="xs:string"/>
<xs:attribute name="driverName" type="xs:string"/>
<xs:attribute name="driverUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:simpleType name="MobileObjectType">
<xs:restriction base="xs:string">
<xs:enumeration value="TRAILER"/>
<xs:enumeration value="VEHICLE"/>
</xs:restriction>
</xs:simpleType>
</xs:schema>
<xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://connect.webfleet.tomtomwork.com/services" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns2="http://connect.webfleet.tomtomwork.com/parameters" xmlns:ns1="http://connect.webfleet.tomtomwork.com/parameters/objects" xmlns="http://connect.webfleet.tomtomwork.com/parameters/auxdevicedata" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://connect.webfleet.tomtomwork.com/parameters/auxdevicedata">
<xs:import namespace="http://connect.webfleet.tomtomwork.com/parameters/objects"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/parameters"/>
<xs:complexType name="ObjectFeaturesParameter">
<xs:complexContent>
<xs:extension base="ns2:ParameterBase">
<xs:sequence>
<xs:element minOccurs="0" name="object" nillable="true" type="ns1:ObjectIdentityParameter"/>
<xs:element minOccurs="0" name="feature" nillable="true" type="ns1:ObjectFeatureType"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
</xs:schema>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://connect.webfleet.tomtomwork.com/transfer/positions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns2="http://connect.webfleet.tomtomwork.com/transfer/addresses" xmlns:ns1="http://connect.webfleet.tomtomwork.com/transfer" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://connect.webfleet.tomtomwork.com/transfer/positions">
<import xmlns="http://www.w3.org/2001/XMLSchema" namespace="http://www.w3.org/2001/XMLSchema-instance"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer/addresses"/>
<xs:complexType name="BasicGeoPosition">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="latitude" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="longitude" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="mapcode" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="GeoPosition">
<xs:complexContent>
<xs:extension base="tns:BasicGeoPosition">
<xs:sequence>
<xs:element minOccurs="0" name="latitudeHumanReadable" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="longitudeHumanReadable" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="NavDestination">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="navTargetLatitude" type="xs:int"/>
<xs:element minOccurs="0" name="navTargetLongitude" type="xs:int"/>
<xs:element minOccurs="0" name="navEtaTime" type="xs:dateTime"/>
<xs:element minOccurs="0" name="navDestination" type="xs:string"/>
<xs:element minOccurs="0" name="distanceToDestination" type="xs:long"/>
<xs:element minOccurs="0" name="isFromOrder" type="xs:boolean"/>
<xs:element minOccurs="0" name="navTargetAddress" type="ns2:AddressIdentity"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="BasicStartAndEndPosition">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="startPosText" type="xs:string"/>
<xs:element minOccurs="0" name="startDateAndTime" type="xs:dateTime"/>
<xs:element minOccurs="0" name="endPosText" type="xs:string"/>
<xs:element minOccurs="0" name="endDateAndTime" type="xs:dateTime"/>
<xs:element minOccurs="0" name="duration" type="xs:long"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="BasicStartAndEndPosWithCoordinates">
<xs:complexContent>
<xs:extension base="tns:BasicStartAndEndPosition">
<xs:sequence>
<xs:element minOccurs="0" name="startPos" nillable="true" type="tns:BasicGeoPosition"/>
<xs:element minOccurs="0" name="endPos" nillable="true" type="tns:BasicGeoPosition"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="StartAndEndPosition">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="startOdometer" type="xs:int"/>
<xs:element minOccurs="0" name="startPosText" type="xs:string"/>
<xs:element minOccurs="0" name="startDateAndTime" type="xs:dateTime"/>
<xs:element minOccurs="0" name="endOdometer" type="xs:int"/>
<xs:element minOccurs="0" name="endPosText" type="xs:string"/>
<xs:element minOccurs="0" name="endDateAndTime" type="xs:dateTime"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="StartAndEndPosWithCoordinates">
<xs:complexContent>
<xs:extension base="tns:StartAndEndPosition">
<xs:sequence>
<xs:element minOccurs="0" name="startPos" nillable="true" type="tns:GeoPosition"/>
<xs:element minOccurs="0" name="endPos" nillable="true" type="tns:GeoPosition"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="Travel">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="speed" type="xs:int"/>
<xs:element minOccurs="0" name="course" type="xs:int"/>
<xs:element minOccurs="0" name="direction" type="tns:IntercardinalDirections"/>
<xs:element minOccurs="0" name="odometer" type="xs:int"/>
<xs:element minOccurs="0" name="estimatedArrivalTime" type="xs:dateTime"/>
<xs:element minOccurs="0" name="distance" type="xs:int"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:simpleType name="IntercardinalDirections">
<xs:restriction base="xs:string">
<xs:enumeration value="NORTH"/>
<xs:enumeration value="NORTHEAST"/>
<xs:enumeration value="EAST"/>
<xs:enumeration value="SOUTHEAST"/>
<xs:enumeration value="SOUTH"/>
<xs:enumeration value="SOUTHWEST"/>
<xs:enumeration value="WEST"/>
<xs:enumeration value="NORTHWEST"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="GPSSignalStatus">
<xs:restriction base="xs:string">
<xs:enumeration value="OK"/>
<xs:enumeration value="WARN"/>
<xs:enumeration value="LAST"/>
<xs:enumeration value="INVALID"/>
</xs:restriction>
</xs:simpleType>
</xs:schema>
<xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://connect.webfleet.tomtomwork.com/services" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns3="http://connect.webfleet.tomtomwork.com/parameters/auxdevicedata" xmlns:ns2="http://connect.webfleet.tomtomwork.com/transfer" xmlns:ns1="http://connect.webfleet.tomtomwork.com/parameters/objects" xmlns:ns0="http://connect.webfleet.tomtomwork.com/parameters" xmlns="http://connect.webfleet.tomtomwork.com/services" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://connect.webfleet.tomtomwork.com/services">
<xs:import namespace="http://connect.webfleet.tomtomwork.com/parameters"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/parameters/objects"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/parameters/auxdevicedata"/>
<xs:complexType abstract="true" name="timeZone">
<xs:sequence>
<xs:element minOccurs="0" name="ID" type="xs:string"/>
<xs:element name="rawOffset" type="xs:int"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showNearestVehicles" type="showNearestVehicles"/>
<xs:complexType name="showNearestVehicles">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="objectGroupNameFilter" type="ns1:ObjectGroupNameParameter"/>
<xs:element minOccurs="0" name="nearestVehicleParameter" type="ns1:NearestVehicleParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showNearestVehiclesResponse" type="showNearestVehiclesResponse"/>
<xs:complexType name="showNearestVehiclesResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceQueryOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="insertObjectGroup" type="insertObjectGroup"/>
<xs:complexType name="insertObjectGroup">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="insertObjectGroup" type="ns1:InsertObjectGroupParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="insertObjectGroupResponse" type="insertObjectGroupResponse"/>
<xs:complexType name="insertObjectGroupResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceWriteOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showObjectGroupObjectReport" type="showObjectGroupObjectReport"/>
<xs:complexType name="showObjectGroupObjectReport">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="showObjectGroupReport" type="ns0:FilterParameter"/>
<xs:element minOccurs="0" name="objectAndGroupFilter" type="ns1:ObjectAndObjectGroupFilterParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showObjectGroupObjectReportResponse" type="showObjectGroupObjectReportResponse"/>
<xs:complexType name="showObjectGroupObjectReportResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceQueryOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showDriverReport" type="showDriverReport"/>
<xs:complexType name="showDriverReport">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="driverFilter" type="ns1:DriverFilterParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showDriverReportResponse" type="showDriverReportResponse"/>
<xs:complexType name="showDriverReportResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceQueryOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showObjectReport" type="showObjectReport"/>
<xs:complexType name="showObjectReport">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="objectFilter" type="ns1:ObjectFilterParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showObjectReportResponse" type="showObjectReportResponse"/>
<xs:complexType name="showObjectReportResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceQueryOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="getObjectFeatures" type="getObjectFeatures"/>
<xs:complexType name="getObjectFeatures">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="objectFeaturesParameter" type="ns3:ObjectFeaturesParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="getObjectFeaturesResponse" type="getObjectFeaturesResponse"/>
<xs:complexType name="getObjectFeaturesResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceQueryOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showVehicleReport" type="showVehicleReport"/>
<xs:complexType name="showVehicleReport">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="objectFilter" type="ns1:ObjectFilterParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showVehicleReportResponse" type="showVehicleReportResponse"/>
<xs:complexType name="showVehicleReportResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceQueryOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="deleteObjectGroup" type="deleteObjectGroup"/>
<xs:complexType name="deleteObjectGroup">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="deleteObjectGroup" type="ns1:DeleteObjectGroupParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="deleteObjectGroupResponse" type="deleteObjectGroupResponse"/>
<xs:complexType name="deleteObjectGroupResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceWriteOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="updateWakeupTimers" type="updateWakeupTimers"/>
<xs:complexType name="updateWakeupTimers">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="wakeupTimers" type="ns1:UpdateWakeupTimersParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="updateWakeupTimersResponse" type="updateWakeupTimersResponse"/>
<xs:complexType name="updateWakeupTimersResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceWriteOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="attachObjectToGroup" type="attachObjectToGroup"/>
<xs:complexType name="attachObjectToGroup">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="attachObjectToGroup" type="ns1:ObjectToGroupParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="attachObjectToGroupResponse" type="attachObjectToGroupResponse"/>
<xs:complexType name="attachObjectToGroupResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceWriteOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="switchOutput" type="switchOutput"/>
<xs:complexType name="switchOutput">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="switchOutput" type="ns1:SwitchOutputParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="switchOutputResponse" type="switchOutputResponse"/>
<xs:complexType name="switchOutputResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceWriteOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="updateObjectGroup" type="updateObjectGroup"/>
<xs:complexType name="updateObjectGroup">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="updateObjectGroup" type="ns1:UpdateObjectGroupParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="updateObjectGroupResponse" type="updateObjectGroupResponse"/>
<xs:complexType name="updateObjectGroupResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceWriteOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showContracts" type="showContracts"/>
<xs:complexType name="showContracts">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="objectFilter" type="ns1:ObjectIdentityParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showContractsResponse" type="showContractsResponse"/>
<xs:complexType name="showContractsResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceQueryOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showObjectGroupReport" type="showObjectGroupReport"/>
<xs:complexType name="showObjectGroupReport">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="showObjectGroupReport" type="ns0:FilterParameter"/>
<xs:element minOccurs="0" name="objectGroupNameFilter" type="ns1:ObjectGroupNameParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showObjectGroupReportResponse" type="showObjectGroupReportResponse"/>
<xs:complexType name="showObjectGroupReportResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceQueryOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="detachObjectFromGroup" type="detachObjectFromGroup"/>
<xs:complexType name="detachObjectFromGroup">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="detachObjectFromGroup" type="ns1:ObjectToGroupParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="detachObjectFromGroupResponse" type="detachObjectFromGroupResponse"/>
<xs:complexType name="detachObjectFromGroupResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceWriteOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="updateVehicle" type="updateVehicle"/>
<xs:complexType name="updateVehicle">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="objectDetails" type="ns1:DetailedVehicleParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="updateVehicleResponse" type="updateVehicleResponse"/>
<xs:complexType name="updateVehicleResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceQueryOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="updateContractInfo" type="updateContractInfo"/>
<xs:complexType name="updateContractInfo">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="updateContractInfoParameter" type="ns1:UpdateContractInfoParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="updateContractInfoResponse" type="updateContractInfoResponse"/>
<xs:complexType name="updateContractInfoResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceWriteOpResult"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showWakeupTimers" type="showWakeupTimers"/>
<xs:complexType name="showWakeupTimers">
<xs:sequence>
<xs:element minOccurs="0" name="aParm" type="ns0:AuthenticationParameters"/>
<xs:element minOccurs="0" name="gParm" type="ns0:GeneralParameters"/>
<xs:element minOccurs="0" name="object" type="ns1:ObjectIdentityParameter"/>
</xs:sequence>
</xs:complexType>
<xs:element name="showWakeupTimersResponse" type="showWakeupTimersResponse"/>
<xs:complexType name="showWakeupTimersResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="ns2:GenericServiceQueryOpResult"/>
</xs:sequence>
</xs:complexType>
</xs:schema>
<xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://connect.webfleet.tomtomwork.com/services" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns2="http://connect.webfleet.tomtomwork.com/transfer" xmlns:ns1="http://connect.webfleet.tomtomwork.com/transfer/positions" xmlns="http://connect.webfleet.tomtomwork.com/transfer/orders" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://connect.webfleet.tomtomwork.com/transfer/orders">
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer/positions"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer"/>
<xs:complexType name="BasicPosition">
<xs:complexContent>
<xs:extension base="ns2:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="geoPosition" nillable="true" type="ns1:GeoPosition"/>
<xs:element minOccurs="0" name="dateAndTime" type="xs:dateTime"/>
<xs:element minOccurs="0" name="textualRepresentation" type="xs:string"/>
<xs:element minOccurs="0" name="shortTextualRepresentation" type="xs:string"/>
</xs:sequence>
<xs:attribute name="type" type="xs:int"/>
<xs:attribute name="altitude" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="GPSFix">
<xs:complexContent>
<xs:extension base="ns2:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="quality" type="xs:string"/>
<xs:element minOccurs="0" name="satellite" type="xs:string"/>
<xs:element minOccurs="0" name="signalStatus" type="ns1:GPSSignalStatus"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
</xs:schema>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://connect.webfleet.tomtomwork.com/transfer/addresses" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns2="http://connect.webfleet.tomtomwork.com/transfer/positions" xmlns:ns1="http://connect.webfleet.tomtomwork.com/transfer" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://connect.webfleet.tomtomwork.com/transfer/addresses">
<import xmlns="http://www.w3.org/2001/XMLSchema" namespace="http://www.w3.org/2001/XMLSchema-instance"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer/positions"/>
<xs:complexType name="BasicLocation">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="street" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="postcode" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="city" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="country" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="PhoneContact">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element minOccurs="0" name="phoneBusiness" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="phoneMobile" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="phonePersonal" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="AddressIdentity">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence/>
<xs:attribute name="addressNo" type="xs:string" use="required"/>
<xs:attribute name="addressUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="Address">
<xs:complexContent>
<xs:extension base="tns:AddressIdentity">
<xs:sequence>
<xs:element name="name1" type="xs:string"/>
<xs:element minOccurs="0" name="name2" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="name3" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="info" type="xs:string"/>
<xs:element default="0" minOccurs="0" name="radius" type="xs:int"/>
<xs:element default="1" minOccurs="0" name="visible" type="xs:int"/>
<xs:element minOccurs="0" name="location" type="tns:DescribedLocation"/>
<xs:element minOccurs="0" name="contact" type="tns:ContactData"/>
<xs:element minOccurs="0" name="colour" nillable="true" type="tns:AddressColour"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DescribedLocation">
<xs:complexContent>
<xs:extension base="tns:Location">
<xs:sequence>
<xs:element minOccurs="0" name="description" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="addrRegion" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="Location">
<xs:complexContent>
<xs:extension base="tns:BasicLocation">
<xs:sequence>
<xs:element minOccurs="0" name="geoPosition" nillable="true" type="ns2:GeoPosition"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ContactData">
<xs:complexContent>
<xs:extension base="tns:PhoneContact">
<xs:sequence>
<xs:element minOccurs="0" name="contactName" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="fax" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="emailAddress" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="AddressGroup">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence/>
<xs:attribute name="uniqueName" type="xs:string" use="required"/>
<xs:attribute name="addressGroupUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="AddressToGroup">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element name="address" type="tns:AddressIdentity"/>
<xs:element name="group" type="tns:AddressGroup"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="AddressToGroupRelationship">
<xs:complexContent>
<xs:extension base="ns1:TransferObjectBase">
<xs:sequence>
<xs:element name="address" type="tns:AddressIdentity"/>
<xs:element name="group" type="tns:AddressGroup"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="CompleteLocation">
<xs:complexContent>
<xs:extension base="tns:Location">
<xs:sequence>
<xs:element minOccurs="0" name="streetNumber" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="positionText" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="CompleteLocationWithAdditionalInformation">
<xs:complexContent>
<xs:extension base="tns:CompleteLocation">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="additionalInformation" nillable="true" type="ns1:KeyValuePair"/>
<xs:element minOccurs="0" name="countryCode" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:simpleType name="AddressColour">
<xs:restriction base="xs:string">
<xs:enumeration value="brightblue"/>
<xs:enumeration value="dullorange"/>
<xs:enumeration value="brightorange"/>
<xs:enumeration value="brightpalegreen"/>
<xs:enumeration value="grassgreen"/>
<xs:enumeration value="brightpurple"/>
<xs:enumeration value="darkred"/>
<xs:enumeration value="dullazure"/>
<xs:enumeration value="deeppurple"/>
<xs:enumeration value="brightazure"/>
<xs:enumeration value="orangehighlight"/>
<xs:enumeration value="brightgreen"/>
<xs:enumeration value="brightorangehighlight"/>
<xs:enumeration value="khaki"/>
<xs:enumeration value="paleblue"/>
<xs:enumeration value="turquoise"/>
</xs:restriction>
</xs:simpleType>
</xs:schema>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://connect.webfleet.tomtomwork.com/parameters" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://connect.webfleet.tomtomwork.com/parameters">
<import xmlns="http://www.w3.org/2001/XMLSchema" namespace="http://www.w3.org/2001/XMLSchema-instance"/>
<xs:complexType name="AuthenticationParameters">
<xs:complexContent>
<xs:extension base="tns:ParameterBase">
<xs:sequence>
<xs:element default="" minOccurs="0" name="accountName" nillable="true" type="xs:string"/>
<xs:element default="" minOccurs="0" name="sessionToken" nillable="true" type="xs:string"/>
<xs:element default="" minOccurs="0" name="userName" nillable="true" type="xs:string"/>
<xs:element default="" minOccurs="0" name="password" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="apiKey" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType abstract="true" name="ParameterBase">
<xs:sequence/>
</xs:complexType>
<xs:complexType name="GeneralParameters">
<xs:complexContent>
<xs:extension base="tns:ParameterBase">
<xs:sequence>
<xs:element default="UK" minOccurs="0" name="locale" type="tns:KnownLocales"/>
<xs:element default="Europe_London" minOccurs="0" name="timeZone" type="tns:KnownTimeZones"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="FilterParameter">
<xs:complexContent>
<xs:extension base="tns:ParameterBase">
<xs:sequence>
<xs:element default="" minOccurs="0" name="filterCriterion" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ManagedFloatParameter">
<xs:complexContent>
<xs:extension base="tns:ParameterBase">
<xs:sequence/>
<xs:attribute name="value" type="xs:float"/>
<xs:attribute name="setNull" type="xs:boolean" use="required"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ManagedIntegerParameter">
<xs:complexContent>
<xs:extension base="tns:ParameterBase">
<xs:sequence/>
<xs:attribute name="value" type="xs:int"/>
<xs:attribute name="setNull" type="xs:boolean" use="required"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DateRange">
<xs:complexContent>
<xs:extension base="tns:ParameterBase">
<xs:sequence>
<xs:element minOccurs="0" name="from" nillable="true" type="xs:dateTime"/>
<xs:element minOccurs="0" name="to" nillable="true" type="xs:dateTime"/>
<xs:element minOccurs="0" name="year" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="month" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="day" nillable="true" type="xs:int"/>
</xs:sequence>
<xs:attribute name="rangePattern" type="tns:DateRangePattern"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType abstract="true" name="ResultQuantifierParameter">
<xs:complexContent>
<xs:extension base="tns:ParameterBase">
<xs:sequence>
<xs:element default="false" name="retrieveIdOnly" type="xs:boolean"/>
<xs:element default="true" name="retrieveShallowestValues" type="xs:boolean"/>
<xs:element default="false" name="retrieveMostCompleteValues" type="xs:boolean"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ManagedEventLevelParameter">
<xs:complexContent>
<xs:extension base="tns:ParameterBase">
<xs:sequence/>
<xs:attribute name="value" type="tns:EventLevel"/>
<xs:attribute name="setNull" type="xs:boolean" use="required"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverVehicleAssignmentParameter">
<xs:complexContent>
<xs:extension base="tns:ParameterBase">
<xs:sequence>
<xs:element minOccurs="0" name="driverNo" type="xs:string"/>
<xs:element default="" minOccurs="0" name="objectNo" type="xs:string"/>
</xs:sequence>
<xs:attribute name="objectUid" type="xs:string"/>
<xs:attribute name="driverUid" type="xs:string"/>
<xs:attribute name="driverRole" type="xs:int"/>
<xs:attribute name="eventTime" type="xs:long"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:simpleType name="KnownLocales">
<xs:restriction base="xs:string">
<xs:enumeration value="UK"/>
<xs:enumeration value="DE"/>
<xs:enumeration value="FR"/>
<xs:enumeration value="ES"/>
<xs:enumeration value="DK"/>
<xs:enumeration value="IT"/>
<xs:enumeration value="NO"/>
<xs:enumeration value="RU"/>
<xs:enumeration value="PL"/>
<xs:enumeration value="US"/>
<xs:enumeration value="UAE"/>
<xs:enumeration value="NL"/>
<xs:enumeration value="ZA"/>
<xs:enumeration value="NA"/>
<xs:enumeration value="MZ"/>
<xs:enumeration value="ZM"/>
<xs:enumeration value="ZW"/>
<xs:enumeration value="TZ"/>
<xs:enumeration value="KE"/>
<xs:enumeration value="AU"/>
<xs:enumeration value="NZ"/>
<xs:enumeration value="IN"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="KnownTimeZones">
<xs:restriction base="xs:string">
<xs:enumeration value="Etc_UTC"/>
<xs:enumeration value="Europe_Amsterdam"/>
<xs:enumeration value="Europe_Andorra"/>
<xs:enumeration value="Europe_Belgrade"/>
<xs:enumeration value="Europe_Berlin"/>
<xs:enumeration value="Europe_Bratislava"/>
<xs:enumeration value="Europe_Brussels"/>
<xs:enumeration value="Europe_Budapest"/>
<xs:enumeration value="Europe_Copenhagen"/>
<xs:enumeration value="Europe_Gibraltar"/>
<xs:enumeration value="Europe_Ljubljana"/>
<xs:enumeration value="Europe_Luxembourg"/>
<xs:enumeration value="Europe_Madrid"/>
<xs:enumeration value="Europe_Malta"/>
<xs:enumeration value="Europe_Monaco"/>
<xs:enumeration value="Europe_Oslo"/>
<xs:enumeration value="Europe_Paris"/>
<xs:enumeration value="Europe_Prague"/>
<xs:enumeration value="Europe_Rome"/>
<xs:enumeration value="Europe_San_Marino"/>
<xs:enumeration value="Europe_Sarajevo"/>
<xs:enumeration value="Europe_Skopje"/>
<xs:enumeration value="Europe_Stockholm"/>
<xs:enumeration value="Europe_Tirane"/>
<xs:enumeration value="Europe_Vaduz"/>
<xs:enumeration value="Europe_Vatican"/>
<xs:enumeration value="Europe_Vienna"/>
<xs:enumeration value="Europe_Warsaw"/>
<xs:enumeration value="Europe_Zagreb"/>
<xs:enumeration value="Europe_Zurich"/>
<xs:enumeration value="Europe_Belfast"/>
<xs:enumeration value="Europe_Dublin"/>
<xs:enumeration value="Europe_Lisbon"/>
<xs:enumeration value="Europe_London"/>
<xs:enumeration value="Europe_Athens"/>
<xs:enumeration value="Europe_Bucharest"/>
<xs:enumeration value="Europe_Helsinki"/>
<xs:enumeration value="Europe_Istanbul"/>
<xs:enumeration value="Europe_Kiev"/>
<xs:enumeration value="Europe_Minsk"/>
<xs:enumeration value="Europe_Nicosia"/>
<xs:enumeration value="Europe_Riga"/>
<xs:enumeration value="Europe_Sofia"/>
<xs:enumeration value="Europe_Tallinn"/>
<xs:enumeration value="Europe_Vilnius"/>
<xs:enumeration value="Europe_Moscow"/>
<xs:enumeration value="Atlantic_Reykjavik"/>
<xs:enumeration value="America_Halifax"/>
<xs:enumeration value="America_Winnipeg"/>
<xs:enumeration value="America_Toronto"/>
<xs:enumeration value="America_Edmonton"/>
<xs:enumeration value="America_St_Johns"/>
<xs:enumeration value="America_Vancouver"/>
<xs:enumeration value="America_Regina"/>
<xs:enumeration value="America_Whitehorse"/>
<xs:enumeration value="America_Puerto_Rico"/>
<xs:enumeration value="America_Chicago"/>
<xs:enumeration value="America_New_York"/>
<xs:enumeration value="America_Denver"/>
<xs:enumeration value="America_Los_Angeles"/>
<xs:enumeration value="America_Anchorage"/>
<xs:enumeration value="America_Adak"/>
<xs:enumeration value="Pacific_Honolulu"/>
<xs:enumeration value="Asia_Tokyo"/>
<xs:enumeration value="Asia_Dubai"/>
<xs:enumeration value="Asia_Hong_Kong"/>
<xs:enumeration value="Asia_Shanghai"/>
<xs:enumeration value="Asia_Taipei"/>
<xs:enumeration value="Asia_Seoul"/>
<xs:enumeration value="Asia_Jerusalem"/>
<xs:enumeration value="Africa_Johannesburg"/>
<xs:enumeration value="Africa_Windhoek"/>
<xs:enumeration value="Africa_Maputo"/>
<xs:enumeration value="Africa_Lusaka"/>
<xs:enumeration value="Africa_Harare"/>
<xs:enumeration value="Africa_Dar_es_Salaam"/>
<xs:enumeration value="Africa_Nairobi"/>
<xs:enumeration value="Australia_ACT"/>
<xs:enumeration value="Australia_Adelaide"/>
<xs:enumeration value="Australia_Brisbane"/>
<xs:enumeration value="Australia_Broken_Hill"/>
<xs:enumeration value="Australia_Canberra"/>
<xs:enumeration value="Australia_Currie"/>
<xs:enumeration value="Australia_Darwin"/>
<xs:enumeration value="Australia_Eucla"/>
<xs:enumeration value="Australia_Hobart"/>
<xs:enumeration value="Australia_LHI"/>
<xs:enumeration value="Australia_Lindeman"/>
<xs:enumeration value="Australia_Lord_Howe"/>
<xs:enumeration value="Australia_Melbourne"/>
<xs:enumeration value="Australia_NSW"/>
<xs:enumeration value="Australia_North"/>
<xs:enumeration value="Australia_Perth"/>
<xs:enumeration value="Australia_Queensland"/>
<xs:enumeration value="Australia_South"/>
<xs:enumeration value="Australia_Sydney"/>
<xs:enumeration value="Australia_Tasmania"/>
<xs:enumeration value="Australia_Victoria"/>
<xs:enumeration value="Australia_West"/>
<xs:enumeration value="Australia_Yancowinna"/>
<xs:enumeration value="Pacific_Auckland"/>
<xs:enumeration value="IST"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="RouteDay">
<xs:restriction base="xs:string">
<xs:enumeration value="today"/>
<xs:enumeration value="tomorrow"/>
<xs:enumeration value="mon"/>
<xs:enumeration value="tue"/>
<xs:enumeration value="wed"/>
<xs:enumeration value="thu"/>
<xs:enumeration value="fri"/>
<xs:enumeration value="sat"/>
<xs:enumeration value="sun"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="DateRangePattern">
<xs:restriction base="xs:string">
<xs:enumeration value="UD"/>
<xs:enumeration value="D0"/>
<xs:enumeration value="Dm1"/>
<xs:enumeration value="Dm2"/>
<xs:enumeration value="Dm3"/>
<xs:enumeration value="Dm4"/>
<xs:enumeration value="Dm5"/>
<xs:enumeration value="Dm6"/>
<xs:enumeration value="W0"/>
<xs:enumeration value="Wm1"/>
<xs:enumeration value="Wm2"/>
<xs:enumeration value="Wm3"/>
<xs:enumeration value="WF0"/>
<xs:enumeration value="WFm1"/>
<xs:enumeration value="WFm2"/>
<xs:enumeration value="WFm3"/>
<xs:enumeration value="M0"/>
<xs:enumeration value="Mm1"/>
<xs:enumeration value="Mm2"/>
<xs:enumeration value="Mm3"/>
<xs:enumeration value="Mm4"/>
<xs:enumeration value="Mm5"/>
<xs:enumeration value="Mm6"/>
<xs:enumeration value="Mm7"/>
<xs:enumeration value="Mm8"/>
<xs:enumeration value="Mm9"/>
<xs:enumeration value="Y0"/>
<xs:enumeration value="Ym1"/>
<xs:enumeration value="Ym2"/>
<xs:enumeration value="Ym3"/>
<xs:enumeration value="Ym4"/>
<xs:enumeration value="Ym5"/>
<xs:enumeration value="Ym6"/>
<xs:enumeration value="Ym7"/>
<xs:enumeration value="Ym8"/>
<xs:enumeration value="Ym9"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="EventLevel">
<xs:restriction base="xs:string">
<xs:enumeration value="I"/>
<xs:enumeration value="W"/>
<xs:enumeration value="A_1"/>
<xs:enumeration value="A_2"/>
<xs:enumeration value="A_3"/>
</xs:restriction>
</xs:simpleType>
</xs:schema>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://connect.webfleet.tomtomwork.com/parameters/objects" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns2="http://connect.webfleet.tomtomwork.com/transfer/objects" xmlns:ns1="http://connect.webfleet.tomtomwork.com/parameters" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://connect.webfleet.tomtomwork.com/parameters/objects">
<import xmlns="http://www.w3.org/2001/XMLSchema" namespace="http://www.w3.org/2001/XMLSchema-instance"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/parameters"/>
<xs:import namespace="http://connect.webfleet.tomtomwork.com/transfer/objects"/>
<xs:complexType name="ObjectGroupNameParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence>
<xs:element minOccurs="0" name="objectGroupName" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="objectGroupUid" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="NearestVehicleParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence>
<xs:element minOccurs="0" name="addrNo" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="latitude" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="longitude" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="priority" nillable="true" type="tns:NearestVehiclePriority"/>
<xs:element minOccurs="0" name="maxDistance" nillable="true" type="xs:int"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="InsertObjectGroupParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="objectGroupName" type="xs:string" use="required"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ObjectAndObjectGroupFilterParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence>
<xs:element minOccurs="0" name="objectGroupName" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="object" nillable="true" type="tns:ObjectIdentityParameter"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ObjectIdentityParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="objectNo" type="xs:string"/>
<xs:attribute name="objectUid" type="xs:string"/>
<xs:attribute name="externalId" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverFilterParameter">
<xs:complexContent>
<xs:extension base="ns1:FilterParameter">
<xs:sequence>
<xs:element minOccurs="0" name="driver" nillable="true" type="tns:DriverIdentityParameter"/>
<xs:element minOccurs="0" name="ungroupedOnly" nillable="true" type="xs:boolean"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverIdentityParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="driverNo" type="xs:string"/>
<xs:attribute name="driverUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ObjectFilterParameter">
<xs:complexContent>
<xs:extension base="ns1:FilterParameter">
<xs:sequence>
<xs:element minOccurs="0" name="objectGroupName" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="object" nillable="true" type="tns:ObjectIdentityParameter"/>
<xs:element minOccurs="0" name="ungroupedOnly" nillable="true" type="xs:boolean"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DeleteObjectGroupParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="objectGroupName" type="xs:string" use="required"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="UpdateWakeupTimersParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence>
<xs:element name="wakeupTimers" type="ns2:WakeupTimersTO"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="ObjectToGroupParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="objectNo" type="xs:string"/>
<xs:attribute name="objectUid" type="xs:string"/>
<xs:attribute name="objectGroupName" type="xs:string" use="required"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="SwitchOutputParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence>
<xs:element default="" minOccurs="0" name="objectNo" type="xs:string"/>
<xs:element name="status" type="xs:int"/>
</xs:sequence>
<xs:attribute name="objectUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="UpdateObjectGroupParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="newObjectGroupName" type="xs:string" use="required"/>
<xs:attribute name="oldObjectGroupName" type="xs:string" use="required"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DetailedVehicleParameter">
<xs:complexContent>
<xs:extension base="ns2:ObjectIdentity">
<xs:sequence>
<xs:element minOccurs="0" name="vehicleType" nillable="true" type="tns:VehicleType"/>
<xs:element minOccurs="0" name="vehicleColor" nillable="true" type="tns:VehicleColour"/>
<xs:element minOccurs="0" name="identNumber" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="registrationDate" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="denotation" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="licensePlateNumber" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="speedLimit" nillable="true" type="ns1:ManagedFloatParameter"/>
<xs:element minOccurs="0" name="fuelConsumption" nillable="true" type="ns1:ManagedFloatParameter"/>
<xs:element minOccurs="0" name="fuelType" nillable="true" type="tns:FuelType"/>
<xs:element minOccurs="0" name="netWeight" nillable="true" type="xs:float"/>
<xs:element minOccurs="0" name="maxWeight" nillable="true" type="xs:float"/>
<xs:element minOccurs="0" name="netLoad" nillable="true" type="xs:float"/>
<xs:element minOccurs="0" name="numAxles" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="length" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="width" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="height" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="description" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="power" nillable="true" type="xs:float"/>
<xs:element minOccurs="0" name="resetFuelAverage" nillable="true" type="xs:boolean"/>
<xs:element minOccurs="0" name="engineSize" nillable="true" type="xs:int"/>
<xs:element minOccurs="0" name="odometer" nillable="true" type="xs:long"/>
<xs:element minOccurs="0" name="rpmLimit" nillable="true" type="ns1:ManagedIntegerParameter"/>
<xs:element minOccurs="0" name="fuelTankSize" nillable="true" type="ns1:ManagedIntegerParameter"/>
<xs:element minOccurs="0" name="epBTAddress" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="rllBTAddress" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="epType" nillable="true" type="tns:EpType"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="UpdateContractInfoParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence>
<xs:element name="object" nillable="true" type="tns:ObjectIdentityParameter"/>
<xs:element minOccurs="0" name="referenceNo" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DeleteDriverParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="driverNo" type="xs:string"/>
<xs:attribute name="driverUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverGroupParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="driverGroupName" type="xs:string" use="required"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverToGroupParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="driverGroupName" type="xs:string" use="required"/>
<xs:attribute name="driverNo" type="xs:string"/>
<xs:attribute name="driverUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="InsertDriverParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="driverNo" type="xs:string" use="required"/>
<xs:attribute name="name" type="xs:string" use="required"/>
<xs:attribute name="name2" type="xs:string"/>
<xs:attribute name="name3" type="xs:string"/>
<xs:attribute name="company" type="xs:string"/>
<xs:attribute name="code" type="xs:string"/>
<xs:attribute name="description" type="xs:string"/>
<xs:attribute name="country" type="xs:string"/>
<xs:attribute name="zip" type="xs:string"/>
<xs:attribute name="city" type="xs:string"/>
<xs:attribute name="street" type="xs:string"/>
<xs:attribute name="telMobile" type="xs:string"/>
<xs:attribute name="telPrivate" type="xs:string"/>
<xs:attribute name="pin" type="xs:string"/>
<xs:attribute name="email" type="xs:string"/>
<xs:attribute name="dtCardId" type="xs:string"/>
<xs:attribute name="dtCardCountry" type="xs:string"/>
<xs:attribute name="rllButtonId" type="xs:string"/>
<xs:attribute name="addressNo" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="UpdateDriverParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence/>
<xs:attribute name="driverNoOld" type="xs:string"/>
<xs:attribute name="driverNo" type="xs:string"/>
<xs:attribute name="name" type="xs:string"/>
<xs:attribute name="name2" type="xs:string"/>
<xs:attribute name="name3" type="xs:string"/>
<xs:attribute name="company" type="xs:string"/>
<xs:attribute name="code" type="xs:string"/>
<xs:attribute name="description" type="xs:string"/>
<xs:attribute name="country" type="xs:string"/>
<xs:attribute name="zip" type="xs:string"/>
<xs:attribute name="city" type="xs:string"/>
<xs:attribute name="street" type="xs:string"/>
<xs:attribute name="telMobile" type="xs:string"/>
<xs:attribute name="telPrivate" type="xs:string"/>
<xs:attribute name="pin" type="xs:string"/>
<xs:attribute name="email" type="xs:string"/>
<xs:attribute name="dtCardId" type="xs:string"/>
<xs:attribute name="dtCardCountry" type="xs:string"/>
<xs:attribute name="rllButtonId" type="xs:string"/>
<xs:attribute name="addressNo" type="xs:string"/>
<xs:attribute name="driverUid" type="xs:string"/>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:complexType name="DriverAndDriverGroupFilterParameter">
<xs:complexContent>
<xs:extension base="ns1:ParameterBase">
<xs:sequence>
<xs:element minOccurs="0" name="driver" nillable="true" type="tns:DriverIdentityParameter"/>
<xs:element minOccurs="0" name="driverGroupName" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
<xs:simpleType name="NearestVehiclePriority">
<xs:restriction base="xs:string">
<xs:enumeration value="OBJECT_STATE"/>
<xs:enumeration value="LINEAR_DISTANCE"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="objectState">
<xs:restriction base="xs:string">
<xs:enumeration value="AVAILABLE"/>
<xs:enumeration value="HAS_ORDER"/>
<xs:enumeration value="OFFLINE"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="WorkState">
<xs:restriction base="xs:string">
<xs:enumeration value="UNKNOWN"/>
<xs:enumeration value="FREETIME"/>
<xs:enumeration value="PAUSE"/>
<xs:enumeration value="STANDBY"/>
<xs:enumeration value="WORKING"/>
<xs:enumeration value="DRIVING"/>
<xs:enumeration value="OTHER_WORK"/>
<xs:enumeration value="SLEEPER_BERTH"/>
<xs:enumeration value="ON_DUTY"/>
<xs:enumeration value="OFF_DUTY"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="DriverRole">
<xs:restriction base="xs:string">
<xs:enumeration value="DRIVER"/>
<xs:enumeration value="CO_DRIVER"/>
<xs:enumeration value="WORKER"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="ObjectFeatureType">
<xs:restriction base="xs:string">
<xs:enumeration value="hdtracking"/>
<xs:enumeration value="waypoints"/>
<xs:enumeration value="linkconnect"/>
<xs:enumeration value="pndupgrade"/>
<xs:enumeration value="tachodownload"/>
<xs:enumeration value="drivingtime"/>
<xs:enumeration value="hoursofservice"/>
<xs:enumeration value="roadusagecharges"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="FuelType">
<xs:restriction base="xs:string">
<xs:enumeration value="UNKNOWN"/>
<xs:enumeration value="DIESEL"/>
<xs:enumeration value="GASOLINE"/>
<xs:enumeration value="LPG"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="VehicleColour">
<xs:restriction base="xs:string">
<xs:enumeration value="WHITE"/>
<xs:enumeration value="GREY"/>
<xs:enumeration value="BLACK"/>
<xs:enumeration value="IVORY"/>
<xs:enumeration value="RED"/>
<xs:enumeration value="ORANGE"/>
<xs:enumeration value="YELLOW"/>
<xs:enumeration value="GREEN"/>
<xs:enumeration value="BLUE"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="EpType">
<xs:restriction base="xs:string">
<xs:enumeration value="ECO_PLUS"/>
<xs:enumeration value="LINK_105"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="VehicleType">
<xs:restriction base="xs:string">
<xs:enumeration value="HEAVYWEIGHT_TRUCK_TRAILER"/>
<xs:enumeration value="TANKER_TRUCK"/>
<xs:enumeration value="HEAVY_TRUCK"/>
<xs:enumeration value="MEDIUM_TRUCK"/>
<xs:enumeration value="DUMP_TRUCK"/>
<xs:enumeration value="PALLET_TRUCK"/>
<xs:enumeration value="CONCRETE_LORRY"/>
<xs:enumeration value="DEPOSIT_TIPPER"/>
<xs:enumeration value="GARBAGE_TRUCK"/>
<xs:enumeration value="LOADER"/>
<xs:enumeration value="EXCAVATOR"/>
<xs:enumeration value="WRECKER"/>
<xs:enumeration value="TRUCK_WRECKER"/>
<xs:enumeration value="MULTICAR"/>
<xs:enumeration value="STREET_SWEEPER"/>
<xs:enumeration value="TRACTOR"/>
<xs:enumeration value="HEAVYWEIGHT_TRUCK"/>
<xs:enumeration value="TRUCK_WITH_TRAILER"/>
<xs:enumeration value="TRAILER"/>
<xs:enumeration value="TRUCK_TRAILER"/>
<xs:enumeration value="CRANE"/>
<xs:enumeration value="BUS"/>
<xs:enumeration value="FIRETRUCK"/>
<xs:enumeration value="AMBULANCE"/>
<xs:enumeration value="POLICE"/>
<xs:enumeration value="CADDY"/>
<xs:enumeration value="VAN"/>
<xs:enumeration value="MULTIVAN"/>
<xs:enumeration value="CAR_STATION_WAGON"/>
<xs:enumeration value="PICKUP"/>
<xs:enumeration value="SUV"/>
<xs:enumeration value="TAXI"/>
<xs:enumeration value="CAR"/>
<xs:enumeration value="APE"/>
<xs:enumeration value="VESPA"/>
<xs:enumeration value="BIKE"/>
<xs:enumeration value="CONTAINERSHIP"/>
<xs:enumeration value="LINK"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="OrderAutomation">
<xs:restriction base="xs:string">
<xs:enumeration value="ACCEPT"/>
<xs:enumeration value="START"/>
<xs:enumeration value="NAVIGATING_TO"/>
<xs:enumeration value="SKIPPING_ROUTE_SUMMARY"/>
<xs:enumeration value="DELETE"/>
<xs:enumeration value="NEXT"/>
</xs:restriction>
</xs:simpleType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="switchOutputResponse">
    <wsdl:part element="tns:switchOutputResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="detachObjectFromGroupResponse">
    <wsdl:part element="tns:detachObjectFromGroupResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="deleteObjectGroup">
    <wsdl:part element="tns:deleteObjectGroup" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showWakeupTimersResponse">
    <wsdl:part element="tns:showWakeupTimersResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="attachObjectToGroupResponse">
    <wsdl:part element="tns:attachObjectToGroupResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showVehicleReportResponse">
    <wsdl:part element="tns:showVehicleReportResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showVehicleReport">
    <wsdl:part element="tns:showVehicleReport" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showContracts">
    <wsdl:part element="tns:showContracts" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showDriverReport">
    <wsdl:part element="tns:showDriverReport" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="attachObjectToGroup">
    <wsdl:part element="tns:attachObjectToGroup" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="updateWakeupTimers">
    <wsdl:part element="tns:updateWakeupTimers" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showNearestVehicles">
    <wsdl:part element="tns:showNearestVehicles" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showObjectGroupObjectReportResponse">
    <wsdl:part element="tns:showObjectGroupObjectReportResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showWakeupTimers">
    <wsdl:part element="tns:showWakeupTimers" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showObjectGroupObjectReport">
    <wsdl:part element="tns:showObjectGroupObjectReport" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showContractsResponse">
    <wsdl:part element="tns:showContractsResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getObjectFeatures">
    <wsdl:part element="tns:getObjectFeatures" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="insertObjectGroup">
    <wsdl:part element="tns:insertObjectGroup" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showObjectReportResponse">
    <wsdl:part element="tns:showObjectReportResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="detachObjectFromGroup">
    <wsdl:part element="tns:detachObjectFromGroup" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="updateContractInfo">
    <wsdl:part element="tns:updateContractInfo" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showNearestVehiclesResponse">
    <wsdl:part element="tns:showNearestVehiclesResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showObjectReport">
    <wsdl:part element="tns:showObjectReport" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="updateObjectGroup">
    <wsdl:part element="tns:updateObjectGroup" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="insertObjectGroupResponse">
    <wsdl:part element="tns:insertObjectGroupResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showObjectGroupReportResponse">
    <wsdl:part element="tns:showObjectGroupReportResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="switchOutput">
    <wsdl:part element="tns:switchOutput" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showObjectGroupReport">
    <wsdl:part element="tns:showObjectGroupReport" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="updateVehicle">
    <wsdl:part element="tns:updateVehicle" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="updateVehicleResponse">
    <wsdl:part element="tns:updateVehicleResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="deleteObjectGroupResponse">
    <wsdl:part element="tns:deleteObjectGroupResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getObjectFeaturesResponse">
    <wsdl:part element="tns:getObjectFeaturesResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="updateWakeupTimersResponse">
    <wsdl:part element="tns:updateWakeupTimersResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="updateContractInfoResponse">
    <wsdl:part element="tns:updateContractInfoResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="updateObjectGroupResponse">
    <wsdl:part element="tns:updateObjectGroupResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="showDriverReportResponse">
    <wsdl:part element="tns:showDriverReportResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="objectsAndPeopleReporting">
    <wsdl:operation name="showNearestVehicles">
      <wsdl:input message="tns:showNearestVehicles" name="showNearestVehicles">
    </wsdl:input>
      <wsdl:output message="tns:showNearestVehiclesResponse" name="showNearestVehiclesResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="insertObjectGroup">
      <wsdl:input message="tns:insertObjectGroup" name="insertObjectGroup">
    </wsdl:input>
      <wsdl:output message="tns:insertObjectGroupResponse" name="insertObjectGroupResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showObjectGroupObjectReport">
      <wsdl:input message="tns:showObjectGroupObjectReport" name="showObjectGroupObjectReport">
    </wsdl:input>
      <wsdl:output message="tns:showObjectGroupObjectReportResponse" name="showObjectGroupObjectReportResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showDriverReport">
      <wsdl:input message="tns:showDriverReport" name="showDriverReport">
    </wsdl:input>
      <wsdl:output message="tns:showDriverReportResponse" name="showDriverReportResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showObjectReport">
      <wsdl:input message="tns:showObjectReport" name="showObjectReport">
    </wsdl:input>
      <wsdl:output message="tns:showObjectReportResponse" name="showObjectReportResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getObjectFeatures">
      <wsdl:input message="tns:getObjectFeatures" name="getObjectFeatures">
    </wsdl:input>
      <wsdl:output message="tns:getObjectFeaturesResponse" name="getObjectFeaturesResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showVehicleReport">
      <wsdl:input message="tns:showVehicleReport" name="showVehicleReport">
    </wsdl:input>
      <wsdl:output message="tns:showVehicleReportResponse" name="showVehicleReportResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="deleteObjectGroup">
      <wsdl:input message="tns:deleteObjectGroup" name="deleteObjectGroup">
    </wsdl:input>
      <wsdl:output message="tns:deleteObjectGroupResponse" name="deleteObjectGroupResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateWakeupTimers">
      <wsdl:input message="tns:updateWakeupTimers" name="updateWakeupTimers">
    </wsdl:input>
      <wsdl:output message="tns:updateWakeupTimersResponse" name="updateWakeupTimersResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="attachObjectToGroup">
      <wsdl:input message="tns:attachObjectToGroup" name="attachObjectToGroup">
    </wsdl:input>
      <wsdl:output message="tns:attachObjectToGroupResponse" name="attachObjectToGroupResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="switchOutput">
      <wsdl:input message="tns:switchOutput" name="switchOutput">
    </wsdl:input>
      <wsdl:output message="tns:switchOutputResponse" name="switchOutputResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateObjectGroup">
      <wsdl:input message="tns:updateObjectGroup" name="updateObjectGroup">
    </wsdl:input>
      <wsdl:output message="tns:updateObjectGroupResponse" name="updateObjectGroupResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showContracts">
      <wsdl:input message="tns:showContracts" name="showContracts">
    </wsdl:input>
      <wsdl:output message="tns:showContractsResponse" name="showContractsResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showObjectGroupReport">
      <wsdl:input message="tns:showObjectGroupReport" name="showObjectGroupReport">
    </wsdl:input>
      <wsdl:output message="tns:showObjectGroupReportResponse" name="showObjectGroupReportResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="detachObjectFromGroup">
      <wsdl:input message="tns:detachObjectFromGroup" name="detachObjectFromGroup">
    </wsdl:input>
      <wsdl:output message="tns:detachObjectFromGroupResponse" name="detachObjectFromGroupResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateVehicle">
      <wsdl:input message="tns:updateVehicle" name="updateVehicle">
    </wsdl:input>
      <wsdl:output message="tns:updateVehicleResponse" name="updateVehicleResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateContractInfo">
      <wsdl:input message="tns:updateContractInfo" name="updateContractInfo">
    </wsdl:input>
      <wsdl:output message="tns:updateContractInfoResponse" name="updateContractInfoResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showWakeupTimers">
      <wsdl:input message="tns:showWakeupTimers" name="showWakeupTimers">
    </wsdl:input>
      <wsdl:output message="tns:showWakeupTimersResponse" name="showWakeupTimersResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="objectsAndPeopleReportingServiceSoapBinding" type="tns:objectsAndPeopleReporting">
    <soap12:binding style="document" transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
    <wsdl:operation name="insertObjectGroup">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="insertObjectGroup">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="insertObjectGroupResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showNearestVehicles">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="showNearestVehicles">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="showNearestVehiclesResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showDriverReport">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="showDriverReport">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="showDriverReportResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showObjectGroupObjectReport">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="showObjectGroupObjectReport">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="showObjectGroupObjectReportResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showObjectReport">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="showObjectReport">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="showObjectReportResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getObjectFeatures">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="getObjectFeatures">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getObjectFeaturesResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showVehicleReport">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="showVehicleReport">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="showVehicleReportResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="deleteObjectGroup">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="deleteObjectGroup">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="deleteObjectGroupResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateWakeupTimers">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="updateWakeupTimers">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateWakeupTimersResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="attachObjectToGroup">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="attachObjectToGroup">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="attachObjectToGroupResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="switchOutput">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="switchOutput">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="switchOutputResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateObjectGroup">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="updateObjectGroup">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateObjectGroupResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showContracts">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="showContracts">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="showContractsResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showObjectGroupReport">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="showObjectGroupReport">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="showObjectGroupReportResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="detachObjectFromGroup">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="detachObjectFromGroup">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="detachObjectFromGroupResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateVehicle">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="updateVehicle">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateVehicleResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateContractInfo">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="updateContractInfo">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateContractInfoResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="showWakeupTimers">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="showWakeupTimers">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="showWakeupTimersResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="objectsAndPeopleReportingService">
    <wsdl:port binding="tns:objectsAndPeopleReportingServiceSoapBinding" name="objectsAndPeopleReportingPort">
      <soap12:address location="https://soap.business.tomtom.com/v1.25/objectsAndPeopleReportingService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>